---
# This role installs and configures the Metricly Agent on a RedHat- or Debian-based Linux server. 
# You must first enter your Metricly API key in vars/main.yml
# Alternatively, you can include the apikey on the command line as an extra variable, using:
#   "--extra-vars=metricly_api_key=<your api key>"

- name: Checking whether API key is set
  fail: 
    msg: "Please set Metricly API key before continuing."
  when: metricly_api_key is not string

- name: Checking whether agent is already installed
  stat:
    path: "/opt/netuitive-agent/conf"
  register: agentstat

# Print message to console if skipping repo/package installation 
- debug:
    msg: "Metricly agent is already installed on {{ansible_hostname}}. Skipping installation."
  when: agentstat.stat.exists == True

# Import distro specific repo/package installation tasks
- name: Installing repo and agent
  include_tasks: "{{ ansible_os_family }}.yml"
  when: agentstat.stat.exists == False

- name: Configuring common settings in agent conf file
  lineinfile:
    path: "{{ netuitive_conf_file }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items: "{{ common_configure }}"
  notify: restart agent

- debug:
    msg: "{{ use_simple_collector }}"

- name: Configuring for Base Collector mode
  include_tasks: "BaseCollector.yml"
  when: use_simple_collector == False

- name: Configuring for Simple Collector mode
  include_tasks: "SimpleCollector.yml"
  when: use_simple_collector == True
